<!DOCTYPE html>
<html xmlns="http://www.w3.org/1999/xhtml" lang="en" xml:lang="en"><head>

<meta charset="utf-8">
<meta name="generator" content="quarto-1.8.25">

<meta name="viewport" content="width=device-width, initial-scale=1.0, user-scalable=yes">

<meta name="author" content="Rimlan &amp; Trisha">

<title>Labour-Market Tightness and Slack in Australia</title>
<style>
code{white-space: pre-wrap;}
span.smallcaps{font-variant: small-caps;}
div.columns{display: flex; gap: min(4vw, 1.5em);}
div.column{flex: auto; overflow-x: auto;}
div.hanging-indent{margin-left: 1.5em; text-indent: -1.5em;}
ul.task-list{list-style: none;}
ul.task-list li input[type="checkbox"] {
  width: 0.8em;
  margin: 0 0.8em 0.2em -1em; /* quarto-specific, see https://github.com/quarto-dev/quarto-cli/issues/4556 */ 
  vertical-align: middle;
}
/* CSS for syntax highlighting */
html { -webkit-text-size-adjust: 100%; }
pre > code.sourceCode { white-space: pre; position: relative; }
pre > code.sourceCode > span { display: inline-block; line-height: 1.25; }
pre > code.sourceCode > span:empty { height: 1.2em; }
.sourceCode { overflow: visible; }
code.sourceCode > span { color: inherit; text-decoration: inherit; }
div.sourceCode { margin: 1em 0; }
pre.sourceCode { margin: 0; }
@media screen {
div.sourceCode { overflow: auto; }
}
@media print {
pre > code.sourceCode { white-space: pre-wrap; }
pre > code.sourceCode > span { text-indent: -5em; padding-left: 5em; }
}
pre.numberSource code
  { counter-reset: source-line 0; }
pre.numberSource code > span
  { position: relative; left: -4em; counter-increment: source-line; }
pre.numberSource code > span > a:first-child::before
  { content: counter(source-line);
    position: relative; left: -1em; text-align: right; vertical-align: baseline;
    border: none; display: inline-block;
    -webkit-touch-callout: none; -webkit-user-select: none;
    -khtml-user-select: none; -moz-user-select: none;
    -ms-user-select: none; user-select: none;
    padding: 0 4px; width: 4em;
  }
pre.numberSource { margin-left: 3em;  padding-left: 4px; }
div.sourceCode
  {   }
@media screen {
pre > code.sourceCode > span > a:first-child::before { text-decoration: underline; }
}
/* CSS for citations */
div.csl-bib-body { }
div.csl-entry {
  clear: both;
  margin-bottom: 0em;
}
.hanging-indent div.csl-entry {
  margin-left:2em;
  text-indent:-2em;
}
div.csl-left-margin {
  min-width:2em;
  float:left;
}
div.csl-right-inline {
  margin-left:2em;
  padding-left:1em;
}
div.csl-indent {
  margin-left: 2em;
}</style>


<script src="Report_files/libs/clipboard/clipboard.min.js"></script>
<script src="Report_files/libs/quarto-html/quarto.js" type="module"></script>
<script src="Report_files/libs/quarto-html/tabsets/tabsets.js" type="module"></script>
<script src="Report_files/libs/quarto-html/axe/axe-check.js" type="module"></script>
<script src="Report_files/libs/quarto-html/popper.min.js"></script>
<script src="Report_files/libs/quarto-html/tippy.umd.min.js"></script>
<script src="Report_files/libs/quarto-html/anchor.min.js"></script>
<link href="Report_files/libs/quarto-html/tippy.css" rel="stylesheet">
<link href="Report_files/libs/quarto-html/quarto-syntax-highlighting-7b89279ff1a6dce999919e0e67d4d9ec.css" rel="stylesheet" id="quarto-text-highlighting-styles">
<script src="Report_files/libs/bootstrap/bootstrap.min.js"></script>
<link href="Report_files/libs/bootstrap/bootstrap-icons.css" rel="stylesheet">
<link href="Report_files/libs/bootstrap/bootstrap-d6a003b94517c951b2d65075d42fb01b.min.css" rel="stylesheet" append-hash="true" id="quarto-bootstrap" data-mode="light">

  <script src="https://cdnjs.cloudflare.com/polyfill/v3/polyfill.min.js?features=es6"></script>
  <script src="https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-chtml-full.js" type="text/javascript"></script>

<script type="text/javascript">
const typesetMath = (el) => {
  if (window.MathJax) {
    // MathJax Typeset
    window.MathJax.typeset([el]);
  } else if (window.katex) {
    // KaTeX Render
    var mathElements = el.getElementsByClassName("math");
    var macros = [];
    for (var i = 0; i < mathElements.length; i++) {
      var texText = mathElements[i].firstChild;
      if (mathElements[i].tagName == "SPAN" && texText && texText.data) {
        window.katex.render(texText.data, mathElements[i], {
          displayMode: mathElements[i].classList.contains('display'),
          throwOnError: false,
          macros: macros,
          fleqn: false
        });
      }
    }
  }
}
window.Quarto = {
  typesetMath
};
</script>

</head>

<body class="fullcontent quarto-light">

<div id="quarto-content" class="page-columns page-rows-contents page-layout-article">

<main class="content" id="quarto-document-content">

<header id="title-block-header" class="quarto-title-block default">
<div class="quarto-title">
<h1 class="title">Labour-Market Tightness and Slack in Australia</h1>
</div>



<div class="quarto-title-meta">

    <div>
    <div class="quarto-title-meta-heading">Author</div>
    <div class="quarto-title-meta-contents">
             <p>Rimlan &amp; Trisha </p>
          </div>
  </div>
    
  
    
  </div>
  


</header>


<p><strong>Executive Summary</strong></p>
<p>To be completed after the analyis and discussion are finalised.</p>
<section id="introduction" class="level1">
<h1>1. Introduction</h1>
<section id="background" class="level2">
<h2 class="anchored" data-anchor-id="background">1.1 Background</h2>
<p>The labour market plays an important role in the Australian economy by connecting employers seeking workers with individuals who are available and willing to work. Labour-market conditions change over time as the demand for workers and the availability of labour respond to economic conditions. Understanding these changes requires consideration of both the demand for labour and the extent to which available labour resources are being utilised.</p>
<p>One indicator of labour demand is the number of job vacancies. A higher level of vacancies generally indicates greater demand from employers for additional workers. However, different vacancy measures capture different aspects of recruitment activity. The Australian Bureau of Statistics (ABS) measures job vacancies as jobs that are available for immediate filling on a specific reference date and for which recruitment action has been taken <span class="citation" data-cites="ABS2026JobVacancies">(<a href="#ref-ABS2026JobVacancies" role="doc-biblioref">Australian Bureau of Statistics 2026</a>)</span>. As a result, ABS Job Vacancies represents a stock measure of vacancies at a particular point in time.</p>
<p>Jobs and Skills Australia (JSA) provides another measure of labour demand through the Internet Vacancy Index (IVI). The IVI is a monthly series based on newly lodged online job advertisements from SEEK, CareerOne and Workforce Australia. It provides detailed information by occupation, skill level and geographic area and can be used as an indicator of recruitment activity and labour demand. However, because it measures newly lodged advertisements during each month rather than vacancies existing at a particular point in time, it differs conceptually from the ABS Job Vacancies measure.</p>
<p>Labour demand alone does not provide a complete picture of labour-market conditions. The supply side of the labour market is also important, particularly the amount of labour that is available but not fully utilised. This is commonly described as labour-market slack or labour underutilisation. Unemployment is one measure of unused labour capacity, but it does not capture workers who already have employment but would prefer and are available to work additional hours. The ABS therefore also publishes measures of underemployment and underutilisation. Underutilisation combines unemployment and underemployment and provides a broader measure of unused labour capacity in the labour market.</p>
<p>Considering labour demand and labour-market slack together can provide a more complete view of labour-market conditions. For example, a period with relatively high demand for workers and limited available labour represents different conditions from a period with weak labour demand and substantial unused labour capacity. This motivates examining not only vacancies and slack separately, but also how they move in relation to one another over time.</p>
<p>A related concept is labour-market tightness, which compares labour demand with the availability of workers. In this project, an initial measure of tightness is constructed as the ratio of ABS Job Vacancies to unemployed persons. A higher vacancy-to-unemployment ratio represents more vacancies relative to unemployed workers, while a lower ratio represents fewer vacancies relative to the number of unemployed workers. This measure provides an additional perspective on the balance between labour demand and available labour.</p>
</section>
<section id="research-motivation" class="level2">
<h2 class="anchored" data-anchor-id="research-motivation">1.2 Research Motivation</h2>
<p>Job vacancies, unemployment, underemployment and underutilisation each provide useful information about the Australian labour market, but they measure different aspects of labour-market conditions. Examining any one indicator independently may therefore provide an incomplete picture.</p>
<p>This distinction is particularly relevant when measuring labour-market slack. Unemployment identifies people without employment who satisfy specific job-search and availability criteria, whereas underemployment captures employed people whose labour is not being fully utilised. The ABS defines underemployed workers as employed people who would prefer and are available to work more hours than they currently have. The underutilisation rate provides a broader indicator by combining unemployed and underemployed people relative to the labour force.</p>
<p>The measurement of labour demand also requires careful consideration. The IVI captures the flow of newly lodged online job advertisements, while ABS Job Vacancies measures the stock of vacancies available for immediate filling on a reference date. In addition, the IVI does not represent all recruitment activity in Australia because it only covers advertisements from its contributing online job boards and excludes recruitment through other websites and informal channels. These differences mean that the choice of vacancy measure depends on the purpose of the analysis.</p>
<p>This project is therefore motivated by the need to examine labour demand and labour-market slack jointly rather than treating them as independent indicators. In particular, examining changes in these measures allows the analysis to investigate whether increases or decreases in job vacancies are associated with corresponding changes in unused labour capacity.</p>
<p>Labour-market tightness is also considered as a complementary measure. By relating the stock of job vacancies to the number of unemployed persons, tightness provides information about vacancies relative to the available pool of unemployed workers. This allows the project to investigate both the direct relationship between changes in vacancies and slack and the broader relationship between labour-market tightness and different measures of slack.</p>
</section>
<section id="research-question" class="level2">
<h2 class="anchored" data-anchor-id="research-question">1.3 Research Question</h2>
<p>Based on this motivation, the main research question is:</p>
<p>To what extent are changes in job vacancies associated with changes in labour-market slack in Australia?</p>
<p>The wording of the research question focuses on association rather than causation. The purpose of the analysis is to determine whether movements in labour demand are systematically related to movements in labour-market slack and to examine how this relationship differs depending on the measure of slack considered.</p>
<p>The project considers three measures of labour-market slack: unemployment, underemployment and underutilisation. This allows the relationship to be examined using both a narrower measure of unused labour capacity and broader measures that account for workers who are employed but would prefer additional hours.</p>
<p>Labour-market tightness is examined as a complementary perspective rather than as a replacement for the main vacancy measure. This distinction is important because the research question specifically concerns changes in job vacancies, while tightness incorporates information from both vacancies and unemployment.</p>
</section>
<section id="research-objectives" class="level2">
<h2 class="anchored" data-anchor-id="research-objectives">1.4 Research Objectives</h2>
<p>The project has four main objectives:</p>
<p>To describe how job vacancies and labour-market slack have changed in Australia over the available data period. To compare alternative measures of labour-market slack, including unemployment, underemployment and underutilisation. To examine the association between changes in job vacancies and changes in labour-market slack, including potential lagged relationships. To investigate labour-market tightness as an additional indicator of the balance between labour demand and available labour.</p>
<p>The analysis uses data from the Australian Bureau of Statistics and Jobs and Skills Australia. The IVI is used to examine monthly online recruitment activity, while ABS Job Vacancies and Labour Force data provide measures of vacancies and labour availability. The different data sources are examined carefully because their definitions, frequency and measurement concepts are not identical.</p>
</section>
<section id="report-structure" class="level2">
<h2 class="anchored" data-anchor-id="report-structure">1.5 Report Structure</h2>
<p>The remainder of this report is organised as follows. Section 2 introduces the main labour-market concepts and provides background on labour demand, labour-market slack and labour-market tightness. Section 3 describes the datasets, variable construction and measurement choices used in the analysis. Section 4 presents exploratory analysis of labour demand, slack and tightness in Australia. Section 5 describes the analytical methodology, including the analysis of changes, correlations and potential lagged relationships. Section 6 presents the empirical results, followed by a discussion of their interpretation in Section 7. Section 8 discusses the limitations of the analysis and possible extensions, and Section 9 concludes the report.</p>
</section>
</section>
<section id="labour-market-concepts-and-background" class="level1">
<h1>2. Labour-Market Concepts and Background</h1>
<section id="labour-demand-and-job-vacancies" class="level2">
<h2 class="anchored" data-anchor-id="labour-demand-and-job-vacancies">2.1 Labour Demand and Job Vacancies</h2>
</section>
<section id="labour-market-slack" class="level2">
<h2 class="anchored" data-anchor-id="labour-market-slack">2.2 Labour-Market Slack</h2>
<p>Labour market slack refers to the extent to which available labour resources are not fully utilised. While unemployment captures people who are without employment and actively seeking and avaiable to work, it does not capture all forms o unused labour capacity. Some employed people may wish to work additional hours, while other potential forms of labour underutilisation may not be reflected in the unemployment rate alone.</p>
<p>This project therefore considers three related measures from the Australian Bureau of Statistics (ABS) Labour Force Survey: unemployment, underemployment and underutilisation. Unemployment provides an indicator of the number of people who are not employed but are available for work and actively seeking employment. Underemployment captures employed people who would like and are available to work additional hours. Underutilisation combines unemployment and underemployment and therefore provides a broader measure of labour that is not being fully utilised.</p>
<p>Underutilisation is used in this project as the primary observable proxy for labour market slack. This is because slack is not directly observable as a single variable and underutilisation captures both the absence of employment and insufficient hours among employed people. Unemployment and underemployment are also analysed separately to identify whether changes in overall slack are associated more strongly with changes in the number of people without work or with the availability of additional hours among employed workers.</p>
<p>The use of underutilisation as a proxy does not imply that it represents all unused labour capacity in the economy. Labour market slack can include dimensions that are not fully captured by the ABS measures, such as people who are marginally attached to the labour force or workers whose available hours do not fully reflect their preferred working arrangements. The measures should therefore be interpreted as observable indicators of labour underutilisation rather than a complete measure of all potential labour resources.</p>
<p>Examining labour market slack alongside labour demad provides a basis for assessing how changes in employer demand are associated with the availability of unused labour. In periods of stronger labour demand, slack may decline as more people move into employment or increase their hours. Conversely, weaker labour demand may be associated with higher unemployment or underemployment. The relationship is not necessarily one-to-one, however, because labour market outcomes can also be affected by participation, industry composition, working hours and broader economic conditions.</p>
</section>
<section id="labour-market-tightness" class="level2">
<h2 class="anchored" data-anchor-id="labour-market-tightness">2.3 Labour-Market Tightness</h2>
<p>Labour market tightness describes the balance between the demand for workers and the availability of workers seeking employment. A labour market is generally considered tighter when employers have a relatively large number of vacancies compared with the number of unemployed people available to fill them. Conversely, a less tight labour market occurs when there are fewer vacancies relative to the number of unemployed people.</p>
<p>In this project, labour market tightness is measured using the vacancy to unemployment ratio. The measure is calculated as the number of job vacancies relative to the number of unemployed people:</p>
<p><span class="math display">\[
\text{Labour-Market Tightness} =
\frac{\text{Job Vacancies}}{\text{Unemployed Persons}}
\]</span></p>
<p>A higher ratio indicates that there are more vacancies relative to unemployed people, while a lower ratio indicates that unemployed people are more numerous relative to available vacancies. The measure therefore provides an indicator of the balance between labour demand and the available pool of unemployed workers.</p>
<p>The vacancy to unemployment ratio is useful because considering vacancies and unemployment separately does not fully describe the conditions faced by employers and job seekers. An increase in vacancies may indicate stronger labour demand, but its implications for labour market conditions depend partly on how many unemployed workers are available. Similarly, a decline in unemployment may indicate improving labour market conditions, but the degree of tightness also depends on the number of vacancies available.</p>
<p>In this analyis, the tightness measure is constructed using the seasonally adjusted ABS Job Vacancies series and the seasonally adjusted ABS number of unemployed persons. The resulting measure is examined at a quarterly frequency to investigate its relationship with labour market slack, particularly unemployment, underemployment and underutilisation.</p>
<p>Labour market tightness and labour market slack represent two related but distinct dimensions of labour market conditions. Tightness focuses on the relationship between employer demand and the pool of unemployed workers, whereas slack focuses on the extent to which available labour in underutilised. Examining both measures together provides a broader view of whether changes in labour demand are associated with changes in unused labour capacity in Australia.</p>
</section>
<section id="relationship-between-labour-demand-and-slack" class="level2">
<h2 class="anchored" data-anchor-id="relationship-between-labour-demand-and-slack">2.4 Relationship Between Labour Demand and Slack</h2>
</section>
<section id="australian-labour-market-context" class="level2">
<h2 class="anchored" data-anchor-id="australian-labour-market-context">2.5 Australian Labour-Market Context</h2>
</section>
</section>
<section id="data-and-measurement" class="level1">
<h1>3. Data and Measurement</h1>
<section id="jobs-and-skills-australia-internet-vacancy-index" class="level2">
<h2 class="anchored" data-anchor-id="jobs-and-skills-australia-internet-vacancy-index">3.1 Jobs and Skills Australia Internet Vacancy Index</h2>
<section id="data-source-and-collection" class="level3">
<h3 class="anchored" data-anchor-id="data-source-and-collection">3.1.1 Data Source and Collection</h3>
<p>The Internet Vacancy Index (IVI), published by Jobs and Skills Australia (JSA), is used in this project as a monthly indicator of labour demand in Australia. The IVI measures online job advertisements newly lodged during each reference month on three contributing job boards: SEEK, CareerOne and Workforce Australia <span class="citation" data-cites="JSAIVIMethodology">(<a href="#ref-JSAIVIMethodology" role="doc-biblioref">Jobs and Skills Australia, n.d.</a>)</span>.</p>
<p>The IVI is based on administrative data provided by the contributing job boards rather than data collected through an employer survey. JSA processes the advertisements and classifies them by occupation, skill level and geographical location. Duplicate advertisements posted on the same or multiple contributing job boards are removed during this process <span class="citation" data-cites="JSAIVIMethodology">(<a href="#ref-JSAIVIMethodology" role="doc-biblioref">Jobs and Skills Australia, n.d.</a>)</span>.</p>
</section>
<section id="measurement-and-coverage" class="level3">
<h3 class="anchored" data-anchor-id="measurement-and-coverage">3.1.2 Measurement and Coverage</h3>
<p>The IVI is available as a monthly time series from January 2006. The data provide information by occupation, skill level, state and territory, and regional areas. For the national labour-demand analysis in this project, the seasonally adjusted Australian total series is used.</p>
<p>An important characteristic of the IVI is that it measures newly lodged advertisements during a month. It therefore represents a flow of online recruitment activity rather than the stock of vacancies that remain unfilled at a particular point in time <span class="citation" data-cites="JSAIVIMethodology">(<a href="#ref-JSAIVIMethodology" role="doc-biblioref">Jobs and Skills Australia, n.d.</a>)</span>.</p>
</section>
<section id="limitations-of-the-ivi" class="level3">
<h3 class="anchored" data-anchor-id="limitations-of-the-ivi">3.1.3 Limitations of the IVI</h3>
<p>The IVI does not represent all vacancies in the Australian labour market. It only includes advertisements from the contributing online job boards and therefore excludes recruitment through other job boards, employer websites, social media, newspapers and informal methods such as word of mouth. In addition, one advertisement may represent multiple available positions, while some vacancies may be filled without being advertised online <span class="citation" data-cites="JSAIVIMethodology">(<a href="#ref-JSAIVIMethodology" role="doc-biblioref">Jobs and Skills Australia, n.d.</a>)</span>.</p>
<p>For these reasons, the IVI is interpreted in this project as an indicator of online recruitment activity and labour demand rather than a complete measure of all job vacancies in Australia.</p>
</section>
</section>
<section id="abs-job-vacancies" class="level2">
<h2 class="anchored" data-anchor-id="abs-job-vacancies">3.2 ABS Job Vacancies</h2>
<section id="job-vacancies-survey" class="level3">
<h3 class="anchored" data-anchor-id="job-vacancies-survey">3.2.1 Job Vacancies Survey</h3>
<p>The second measure of labour demand is obtained from the Australian Bureau of Statistics (ABS) Job Vacancies Survey (JVS). Unlike the IVI, which is based on online job advertisements, the JVS collects information directly from a sample of employing organisations. Approximately 4,000 statistical units are selected from the ABS Business Register, with data collected through online electronic collection and/or telephone interviews <span class="citation" data-cites="ABS2026JobVacancies">(<a href="#ref-ABS2026JobVacancies" role="doc-biblioref">Australian Bureau of Statistics 2026</a>)</span>.</p>
<p>The ABS defines a job vacancy as a job that is available for immediate filling on the survey reference date and for which recruitment action has been taken <span class="citation" data-cites="ABS2026JobVacancies">(<a href="#ref-ABS2026JobVacancies" role="doc-biblioref">Australian Bureau of Statistics 2026</a>)</span>.</p>
</section>
<section id="measurement-and-coverage-1" class="level3">
<h3 class="anchored" data-anchor-id="measurement-and-coverage-1">3.2.2 Measurement and Coverage</h3>
<p>The JVS is conducted quarterly. Its reference date is the third Friday of the middle month of each quarter, corresponding to February, May, August and November. The number of vacancies therefore refers to vacancies existing on a particular reference date rather than vacancies accumulated over the entire quarter <span class="citation" data-cites="ABS2026JobVacancies">(<a href="#ref-ABS2026JobVacancies" role="doc-biblioref">Australian Bureau of Statistics 2026</a>)</span>.</p>
<p>For this project, the seasonally adjusted Australian total job-vacancy series is used. ABS classifies job vacancies as a stock measure because they are measured at a specific point in time <span class="citation" data-cites="ABS2026JobVacancies">(<a href="#ref-ABS2026JobVacancies" role="doc-biblioref">Australian Bureau of Statistics 2026</a>)</span>.</p>
<p>There are five missing quarterly observations between August 2008 and August 2009 because the Job Vacancies Survey was suspended after May 2008 and reinstated in November 2009. These observations are retained as missing rather than being imputed, as the ABS does not provide official estimates for the gap period <span class="citation" data-cites="ABS2026JobVacancies">(<a href="#ref-ABS2026JobVacancies" role="doc-biblioref">Australian Bureau of Statistics 2026</a>)</span>.</p>
</section>
<section id="ivi-versus-abs-job-vacancies" class="level3">
<h3 class="anchored" data-anchor-id="ivi-versus-abs-job-vacancies">3.2.3 IVI versus ABS Job Vacancies</h3>
<p>Although both series provide information about labour demand, they measure different concepts. The IVI counts newly lodged online job advertisements during a month and is therefore a flow measure of recruitment activity. In contrast, ABS Job Vacancies measures the number of vacancies available for immediate filling on a particular reference date and is therefore a stock measure <span class="citation" data-cites="JSAIVIMethodology ABS2026JobVacancies">(<a href="#ref-JSAIVIMethodology" role="doc-biblioref">Jobs and Skills Australia, n.d.</a>; <a href="#ref-ABS2026JobVacancies" role="doc-biblioref">Australian Bureau of Statistics 2026</a>)</span>.</p>
<p>This distinction is important for the analysis. The IVI is used to examine monthly changes in recruitment demand, while ABS Job Vacancies is used in constructing the quarterly labour-market tightness measure. Using ABS Job Vacancies for the tightness measure provides a more consistent comparison with the number of unemployed persons, since both represent quantities measured for a particular reference period.</p>
</section>
</section>
<section id="abs-labour-force-data" class="level2">
<h2 class="anchored" data-anchor-id="abs-labour-force-data">3.3 ABS Labour Force Data</h2>
<p>This section describes the ABS Labour Force data used to measure unemployment, underemployment and underutilisation.</p>
<section id="data-source-and-labour-market-measures" class="level3">
<h3 class="anchored" data-anchor-id="data-source-and-labour-market-measures">3.3.1 Data Source and Labour-Market Measures</h3>
<p>The analysis of labour market slack uses data from the Australian Bureau of Statistics (ABS) Labour Force Survey. The Labour Force Survey provides monthly measures of employment, unemployment, undermeployment and labour-force participation for the Australian population aged 15 years and over. These measures provide the basis for constructing observable indicators of labour market slack over time.</p>
<p>Three measures are central to this analysis. The unemployment rate captures the proportion of the labour force that is unemployed, while the underemployment rate captures employed people who want and are available to work additional hours. The underutilisation rate combines unemployment and underemployment and provides a broader measure of labour underutilisation.</p>
<p>The analysis retains unemployment and underemployment as separate measures while using underutilisation as the primary proxy for overall labour market slack. This approach allows the analysis to distinguish between different forms of unused labour capacity rather than relying on unemployment alone.</p>
</section>
<section id="measurement-of-labour-market-slack" class="level3">
<h3 class="anchored" data-anchor-id="measurement-of-labour-market-slack">3.3.2 Measurement of Labour-Market Slack</h3>
<p>Labour market slack is not directly observed as a single variable. Instead, it is approximated using observable measures of labour underutilisation. In this study, underutilisation is used as the main proxy because it incorporates both unemployment and underemployment.</p>
<p>This distinction is important because unemployment alone may understate available labour capacity. An individual who is employed but wants and is available to work additional hours is not classified as unemployed, but their unused working time capacity is captured through underemployment. Including underemployment therefore provides a broader perspective on labour market slack.</p>
<p>The analysis also examines unemployment and underemployment separately. This enables changes in overall underutilisation to be interpreted in terms of whether they are associated primarily with changes in unemployment, changes in the availability of additional working hours, or movements in both measures.</p>
</section>
<section id="data-period-and-frequency" class="level3">
<h3 class="anchored" data-anchor-id="data-period-and-frequency">3.3.3 Data Period and Frequency</h3>
<p>The ABS Labour Force data used in this study contain 582 monthly observations covering the period from February 1978 to July 2026. The long time span allows labour market slack to be examined across different economic conditions and major periods of labour market disruption.</p>
<p>For the historical analysis, the data are grouped into six broad periods: 1978-1989, 1990-1994, 1995-2007, 2008-2019, 2020-2021 and 2022 onwards. These periods provide a basis for comparing labour market conditions across different phases of the Australian economy, including the early 1990s recession and the COVID-19 period.</p>
<p>The monthly frequency of the Labour Force Survey also allows changes in unemployment, underemployment and underutilisation to be examined at a relatively detailed time scale. For the analysis of the labour market tightness, the monthly labour force measures are aligned with the quarterly ABS Job Vacancies data to construct the vacancy to unemployment ratio.</p>
</section>
<section id="measurement-considerations" class="level3">
<h3 class="anchored" data-anchor-id="measurement-considerations">3.3.4 Measurement Considerations</h3>
<p>The ABS Labour Force measures provide consistent and widely used indicators of labour market conditions, but they do not capture every dimension of unused labour capacity. In particular, underutilisation does not represent all potnetial forms of labour market slack, such as the capacity of people who are outside the labour force to enter employment or changes in workers preferred working arrangements that are not reflected in the standard measures.</p>
<p>Underutilisation should thereore be interpreted as an observable proxy for labour market slack rather than a complete measure of unused labour resources. This limitation is important when interpreting the relationship between labour market tightness and slack. The analysis focuses on statistical associations between labour market tightness and slack. The analysis focuses on statistical associations between the measures and does not interpret these relationships as evidence of causality.</p>
</section>
</section>
<section id="labour-market-tightness-1" class="level2">
<h2 class="anchored" data-anchor-id="labour-market-tightness-1">3.4 Labour-Market Tightness</h2>
<section id="vacancy-to-unemployment-ratio" class="level3">
<h3 class="anchored" data-anchor-id="vacancy-to-unemployment-ratio">3.4.1 Vacancy-to-Unemployment Ratio</h3>
<p>Labour-market tightness is used to represent the balance between labour demand and the availability of unemployed workers. In this project, tightness is initially measured using the vacancy-to-unemployment ratio:</p>
<p><span class="math display">\[
\text{Labour-market tightness}_t =
\frac{\text{Job Vacancies}_t}
{\text{Unemployed Persons}_t}
\]</span></p>
<p>A higher value indicates that there are more job vacancies relative to the number of unemployed persons, representing a tighter labour market. Conversely, a lower value indicates fewer vacancies relative to unemployed persons.</p>
</section>
<section id="construction-of-the-measure" class="level3">
<h3 class="anchored" data-anchor-id="construction-of-the-measure">3.4.2 Construction of the Measure</h3>
<p>The numerator is the seasonally adjusted Australian total ABS Job Vacancies series, while the denominator is the seasonally adjusted number of unemployed persons from the ABS Labour Force data.</p>
<p>Because Job Vacancies data are quarterly while Labour Force data are monthly, unemployed-person observations are matched to the corresponding vacancy reference months of February, May, August and November. Both series are measured in thousands of persons or positions, so the units cancel when the ratio is calculated.</p>
<p>The resulting measure provides a quarterly series of labour-market tightness that can subsequently be compared with the measures of labour-market slack used in this project.</p>
</section>
</section>
<section id="abs-job-vacancies-over-time" class="level2">
<h2 class="anchored" data-anchor-id="abs-job-vacancies-over-time">4.1 ABS Job Vacancies Over Time</h2>
<p>The ABS Job Vacancies series provides a quarterly view of labour demand in Australia. Figure <a href="#fig-job-vacancies" class="quarto-xref">Figure&nbsp;1</a> shows the seasonally adjusted number of job vacancies over the study period.</p>
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb1"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb1-1"><a href="#cb1-1" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(tidyverse)</span>
<span id="cb1-2"><a href="#cb1-2" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-3"><a href="#cb1-3" aria-hidden="true" tabindex="-1"></a>job_vacancies <span class="ot">&lt;-</span> <span class="fu">read_csv</span>(</span>
<span id="cb1-4"><a href="#cb1-4" aria-hidden="true" tabindex="-1"></a>  <span class="st">"../data/processed/abs_job_vacancies_clean.csv"</span>,</span>
<span id="cb1-5"><a href="#cb1-5" aria-hidden="true" tabindex="-1"></a>  <span class="at">show_col_types =</span> <span class="cn">FALSE</span></span>
<span id="cb1-6"><a href="#cb1-6" aria-hidden="true" tabindex="-1"></a>) <span class="sc">|&gt;</span></span>
<span id="cb1-7"><a href="#cb1-7" aria-hidden="true" tabindex="-1"></a>  <span class="fu">mutate</span>(<span class="at">Quarter =</span> <span class="fu">as.Date</span>(Quarter))</span>
<span id="cb1-8"><a href="#cb1-8" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-9"><a href="#cb1-9" aria-hidden="true" tabindex="-1"></a><span class="fu">ggplot</span>(job_vacancies, <span class="fu">aes</span>(<span class="at">x =</span> Quarter, <span class="at">y =</span> Job_Vacancies)) <span class="sc">+</span></span>
<span id="cb1-10"><a href="#cb1-10" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_line</span>(<span class="at">linewidth =</span> <span class="fl">0.8</span>) <span class="sc">+</span></span>
<span id="cb1-11"><a href="#cb1-11" aria-hidden="true" tabindex="-1"></a>  <span class="fu">labs</span>(</span>
<span id="cb1-12"><a href="#cb1-12" aria-hidden="true" tabindex="-1"></a>    <span class="at">x =</span> <span class="cn">NULL</span>,</span>
<span id="cb1-13"><a href="#cb1-13" aria-hidden="true" tabindex="-1"></a>    <span class="at">y =</span> <span class="st">"Job vacancies ('000)"</span>,</span>
<span id="cb1-14"><a href="#cb1-14" aria-hidden="true" tabindex="-1"></a>    <span class="at">title =</span> <span class="st">"Job Vacancies in Australia"</span>,</span>
<span id="cb1-15"><a href="#cb1-15" aria-hidden="true" tabindex="-1"></a>    <span class="at">subtitle =</span> <span class="st">"Seasonally adjusted ABS Job Vacancies"</span></span>
<span id="cb1-16"><a href="#cb1-16" aria-hidden="true" tabindex="-1"></a>  ) <span class="sc">+</span></span>
<span id="cb1-17"><a href="#cb1-17" aria-hidden="true" tabindex="-1"></a>  <span class="fu">theme_minimal</span>()</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output-display">
<div id="fig-job-vacancies" class="quarto-float quarto-figure quarto-figure-center anchored">
<figure class="quarto-float quarto-float-fig figure">
<div aria-describedby="fig-job-vacancies-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
<img src="Report_files/figure-html/fig-job-vacancies-1.png" class="img-fluid figure-img" width="672">
</div>
<figcaption class="quarto-float-caption-bottom quarto-float-caption quarto-float-fig" id="fig-job-vacancies-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
Figure&nbsp;1: Seasonally adjusted job vacancies in Australia
</figcaption>
</figure>
</div>
</div>
</div>
<p>Job vacancies changed considerably over the study period. Vacancies declined during the late 2000s, although the series contains a gap between August 2008 and August 2009 due to the suspension of the Job Vacancies Survey during this period <span class="citation" data-cites="ABS2026JobVacancies">(<a href="#ref-ABS2026JobVacancies" role="doc-biblioref">Australian Bureau of Statistics 2026</a>)</span>.</p>
<p>A particularly large decline is visible in 2020, followed by a strong increase during 2021 and 2022. Job vacancies reached their highest levels around 2022 before declining over the following years.</p>
<p>These patterns indicate that labour demand has varied substantially over time. However, the figure is descriptive and does not by itself establish the causes of these movements.</p>
</section>
<section id="internet-vacancy-index-over-time" class="level2">
<h2 class="anchored" data-anchor-id="internet-vacancy-index-over-time">4.2 Internet Vacancy Index Over Time</h2>
<p>The Internet Vacancy Index provides a higher-frequency view of recruitment activity because it records newly lodged online job advertisements each month. Figure <a href="#fig-ivi-total" class="quarto-xref">Figure&nbsp;2</a> shows the seasonally adjusted Australian total IVI.</p>
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb2"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb2-1"><a href="#cb2-1" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(tidyverse)</span>
<span id="cb2-2"><a href="#cb2-2" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb2-3"><a href="#cb2-3" aria-hidden="true" tabindex="-1"></a>ivi_anzsco2 <span class="ot">&lt;-</span> <span class="fu">read_csv</span>(</span>
<span id="cb2-4"><a href="#cb2-4" aria-hidden="true" tabindex="-1"></a>  <span class="st">"../data/processed/ivi_anzsco2_clean.csv"</span>,</span>
<span id="cb2-5"><a href="#cb2-5" aria-hidden="true" tabindex="-1"></a>  <span class="at">show_col_types =</span> <span class="cn">FALSE</span></span>
<span id="cb2-6"><a href="#cb2-6" aria-hidden="true" tabindex="-1"></a>)</span>
<span id="cb2-7"><a href="#cb2-7" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb2-8"><a href="#cb2-8" aria-hidden="true" tabindex="-1"></a>ivi_australia <span class="ot">&lt;-</span> ivi_anzsco2 <span class="sc">|&gt;</span></span>
<span id="cb2-9"><a href="#cb2-9" aria-hidden="true" tabindex="-1"></a>  <span class="fu">filter</span>(</span>
<span id="cb2-10"><a href="#cb2-10" aria-hidden="true" tabindex="-1"></a>    Level <span class="sc">==</span> <span class="dv">1</span>,</span>
<span id="cb2-11"><a href="#cb2-11" aria-hidden="true" tabindex="-1"></a>    ANZSCO_CODE <span class="sc">==</span> <span class="st">"0"</span>,</span>
<span id="cb2-12"><a href="#cb2-12" aria-hidden="true" tabindex="-1"></a>    State <span class="sc">==</span> <span class="st">"AUST"</span></span>
<span id="cb2-13"><a href="#cb2-13" aria-hidden="true" tabindex="-1"></a>  ) <span class="sc">|&gt;</span></span>
<span id="cb2-14"><a href="#cb2-14" aria-hidden="true" tabindex="-1"></a>  <span class="fu">arrange</span>(Month)</span>
<span id="cb2-15"><a href="#cb2-15" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb2-16"><a href="#cb2-16" aria-hidden="true" tabindex="-1"></a><span class="fu">ggplot</span>(ivi_australia, <span class="fu">aes</span>(<span class="at">x =</span> Month, <span class="at">y =</span> Vacancies)) <span class="sc">+</span></span>
<span id="cb2-17"><a href="#cb2-17" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_line</span>(<span class="at">linewidth =</span> <span class="fl">0.8</span>) <span class="sc">+</span></span>
<span id="cb2-18"><a href="#cb2-18" aria-hidden="true" tabindex="-1"></a>  <span class="fu">labs</span>(</span>
<span id="cb2-19"><a href="#cb2-19" aria-hidden="true" tabindex="-1"></a>    <span class="at">x =</span> <span class="cn">NULL</span>,</span>
<span id="cb2-20"><a href="#cb2-20" aria-hidden="true" tabindex="-1"></a>    <span class="at">y =</span> <span class="st">"Online job advertisements"</span>,</span>
<span id="cb2-21"><a href="#cb2-21" aria-hidden="true" tabindex="-1"></a>    <span class="at">title =</span> <span class="st">"Internet Vacancy Index in Australia"</span>,</span>
<span id="cb2-22"><a href="#cb2-22" aria-hidden="true" tabindex="-1"></a>    <span class="at">subtitle =</span> <span class="st">"Seasonally adjusted national series"</span></span>
<span id="cb2-23"><a href="#cb2-23" aria-hidden="true" tabindex="-1"></a>  ) <span class="sc">+</span></span>
<span id="cb2-24"><a href="#cb2-24" aria-hidden="true" tabindex="-1"></a>  <span class="fu">theme_minimal</span>()</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output-display">
<div id="fig-ivi-total" class="quarto-float quarto-figure quarto-figure-center anchored">
<figure class="quarto-float quarto-float-fig figure">
<div aria-describedby="fig-ivi-total-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
<img src="Report_files/figure-html/fig-ivi-total-1.png" class="img-fluid figure-img" width="672">
</div>
<figcaption class="quarto-float-caption-bottom quarto-float-caption quarto-float-fig" id="fig-ivi-total-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
Figure&nbsp;2: Internet Vacancy Index for Australia
</figcaption>
</figure>
</div>
</div>
</div>
<p>The IVI also shows substantial variation in recruitment activity over time. Online job advertisements increased during the earlier part of the series before declining around 2008–2009. Recruitment activity subsequently recovered, although further periods of decline and recovery are visible.</p>
<p>One of the most pronounced movements occurs in 2020, when the IVI falls sharply. This is followed by a strong increase, with recruitment activity reaching particularly high levels around 2022. The index subsequently declines through the following years.</p>
<p>The broad movements are similar to those observed in ABS Job Vacancies. However, the two series should not be interpreted as identical measures. The IVI measures the flow of newly lodged online advertisements each month, whereas ABS Job Vacancies measures the stock of vacancies available for immediate filling at a reference date <span class="citation" data-cites="JSAIVIMethodology ABS2026JobVacancies">(<a href="#ref-JSAIVIMethodology" role="doc-biblioref">Jobs and Skills Australia, n.d.</a>; <a href="#ref-ABS2026JobVacancies" role="doc-biblioref">Australian Bureau of Statistics 2026</a>)</span>.</p>
</section>
<section id="labour-market-slack-over-time" class="level2">
<h2 class="anchored" data-anchor-id="labour-market-slack-over-time">4.3 Labour-Market Slack Over Time</h2>
<p>The ABS Labour Force data provide a long-run view of labour-market slack in Australia. Figure <a href="#fig-labour-market-slack" class="quarto-xref">Figure&nbsp;3</a> presents monthly unemployment, underemployment and underutilisation rates from February 1978 to July 2026. In this analysis, underutilisation is used as the primary observable proxy for labour-market slack, while unemployment and underemployment are examined separately to distinguish the different components of unused labour capacity.</p>
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb3"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb3-1"><a href="#cb3-1" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(tidyverse)</span>
<span id="cb3-2"><a href="#cb3-2" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb3-3"><a href="#cb3-3" aria-hidden="true" tabindex="-1"></a>slack <span class="ot">&lt;-</span> <span class="fu">read_csv</span>(</span>
<span id="cb3-4"><a href="#cb3-4" aria-hidden="true" tabindex="-1"></a>  <span class="st">"/Users/Hp/Desktop/Uni/ETC-5543/Australia-Labor-Market-Project/data/processed/labour_market_slack.csv"</span>,</span>
<span id="cb3-5"><a href="#cb3-5" aria-hidden="true" tabindex="-1"></a>  <span class="at">show_col_types =</span> <span class="cn">FALSE</span></span>
<span id="cb3-6"><a href="#cb3-6" aria-hidden="true" tabindex="-1"></a>)</span>
<span id="cb3-7"><a href="#cb3-7" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb3-8"><a href="#cb3-8" aria-hidden="true" tabindex="-1"></a>slack_long <span class="ot">&lt;-</span> slack <span class="sc">|&gt;</span></span>
<span id="cb3-9"><a href="#cb3-9" aria-hidden="true" tabindex="-1"></a>  <span class="fu">select</span>(</span>
<span id="cb3-10"><a href="#cb3-10" aria-hidden="true" tabindex="-1"></a>    date,</span>
<span id="cb3-11"><a href="#cb3-11" aria-hidden="true" tabindex="-1"></a>    unemployment_rate,</span>
<span id="cb3-12"><a href="#cb3-12" aria-hidden="true" tabindex="-1"></a>    underemployment_rate,</span>
<span id="cb3-13"><a href="#cb3-13" aria-hidden="true" tabindex="-1"></a>    underutilisation_rate</span>
<span id="cb3-14"><a href="#cb3-14" aria-hidden="true" tabindex="-1"></a>  ) <span class="sc">|&gt;</span></span>
<span id="cb3-15"><a href="#cb3-15" aria-hidden="true" tabindex="-1"></a>  <span class="fu">pivot_longer</span>(</span>
<span id="cb3-16"><a href="#cb3-16" aria-hidden="true" tabindex="-1"></a>    <span class="at">cols =</span> <span class="fu">c</span>(</span>
<span id="cb3-17"><a href="#cb3-17" aria-hidden="true" tabindex="-1"></a>      unemployment_rate,</span>
<span id="cb3-18"><a href="#cb3-18" aria-hidden="true" tabindex="-1"></a>      underemployment_rate,</span>
<span id="cb3-19"><a href="#cb3-19" aria-hidden="true" tabindex="-1"></a>      underutilisation_rate</span>
<span id="cb3-20"><a href="#cb3-20" aria-hidden="true" tabindex="-1"></a>    ),</span>
<span id="cb3-21"><a href="#cb3-21" aria-hidden="true" tabindex="-1"></a>    <span class="at">names_to =</span> <span class="st">"measure"</span>,</span>
<span id="cb3-22"><a href="#cb3-22" aria-hidden="true" tabindex="-1"></a>    <span class="at">values_to =</span> <span class="st">"rate"</span></span>
<span id="cb3-23"><a href="#cb3-23" aria-hidden="true" tabindex="-1"></a>  ) <span class="sc">|&gt;</span></span>
<span id="cb3-24"><a href="#cb3-24" aria-hidden="true" tabindex="-1"></a>  <span class="fu">mutate</span>(</span>
<span id="cb3-25"><a href="#cb3-25" aria-hidden="true" tabindex="-1"></a>    <span class="at">measure =</span> <span class="fu">recode</span>(</span>
<span id="cb3-26"><a href="#cb3-26" aria-hidden="true" tabindex="-1"></a>      measure,</span>
<span id="cb3-27"><a href="#cb3-27" aria-hidden="true" tabindex="-1"></a>      <span class="at">unemployment_rate =</span> <span class="st">"Unemployment"</span>,</span>
<span id="cb3-28"><a href="#cb3-28" aria-hidden="true" tabindex="-1"></a>      <span class="at">underemployment_rate =</span> <span class="st">"Underemployment"</span>,</span>
<span id="cb3-29"><a href="#cb3-29" aria-hidden="true" tabindex="-1"></a>      <span class="at">underutilisation_rate =</span> <span class="st">"Underutilisation"</span></span>
<span id="cb3-30"><a href="#cb3-30" aria-hidden="true" tabindex="-1"></a>    )</span>
<span id="cb3-31"><a href="#cb3-31" aria-hidden="true" tabindex="-1"></a>  )</span>
<span id="cb3-32"><a href="#cb3-32" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb3-33"><a href="#cb3-33" aria-hidden="true" tabindex="-1"></a><span class="fu">ggplot</span>(slack_long, <span class="fu">aes</span>(<span class="at">x =</span> date, <span class="at">y =</span> rate, <span class="at">colour =</span> measure)) <span class="sc">+</span></span>
<span id="cb3-34"><a href="#cb3-34" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_line</span>(<span class="at">linewidth =</span> <span class="fl">0.7</span>) <span class="sc">+</span></span>
<span id="cb3-35"><a href="#cb3-35" aria-hidden="true" tabindex="-1"></a>  <span class="fu">labs</span>(</span>
<span id="cb3-36"><a href="#cb3-36" aria-hidden="true" tabindex="-1"></a>    <span class="at">title =</span> <span class="st">"Australian Labour-Market Slack Over Time"</span>,</span>
<span id="cb3-37"><a href="#cb3-37" aria-hidden="true" tabindex="-1"></a>    <span class="at">x =</span> <span class="cn">NULL</span>,</span>
<span id="cb3-38"><a href="#cb3-38" aria-hidden="true" tabindex="-1"></a>    <span class="at">y =</span> <span class="st">"Rate (%)"</span>,</span>
<span id="cb3-39"><a href="#cb3-39" aria-hidden="true" tabindex="-1"></a>    <span class="at">colour =</span> <span class="st">"Measure"</span></span>
<span id="cb3-40"><a href="#cb3-40" aria-hidden="true" tabindex="-1"></a>  ) <span class="sc">+</span></span>
<span id="cb3-41"><a href="#cb3-41" aria-hidden="true" tabindex="-1"></a>  <span class="fu">theme_minimal</span>()</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output-display">
<div id="fig-labour-market-slack" class="quarto-float quarto-figure quarto-figure-center anchored">
<figure class="quarto-float quarto-float-fig figure">
<div aria-describedby="fig-labour-market-slack-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
<img src="Report_files/figure-html/fig-labour-market-slack-1.png" class="img-fluid figure-img" width="672">
</div>
<figcaption class="quarto-float-caption-bottom quarto-float-caption quarto-float-fig" id="fig-labour-market-slack-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
Figure&nbsp;3: Unemployment, underemployment and underutilisation in Australia
</figcaption>
</figure>
</div>
</div>
</div>
<p>The three measures display substantial variation over the study period and illustrate why unemployment alone may not capture the full extent of unused labour capacity. Unemployment measures people who are without work and actively seeking and available for work, whereas underemployment captures employed people who want and are available for additional hours. Underutilisation combines unemployment and underemployment and therefore provides a broader measure of labour underutilisation.</p>
<p>To compare labour-market conditions across different stages of the sample, the analysis divides the period into six broad intervals: 1978–1989, 1990–1994, 1995–2007, 2008–2019, 2020–2021 and 2022 onwards. Table <a href="#tbl-slack-periods" class="quarto-xref">Table&nbsp;1</a> summarises the average unemployment, underemployment and underutilisation rates for each period.</p>
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb4"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb4-1"><a href="#cb4-1" aria-hidden="true" tabindex="-1"></a>period_summary <span class="ot">&lt;-</span> slack <span class="sc">|&gt;</span></span>
<span id="cb4-2"><a href="#cb4-2" aria-hidden="true" tabindex="-1"></a>  <span class="fu">mutate</span>(</span>
<span id="cb4-3"><a href="#cb4-3" aria-hidden="true" tabindex="-1"></a>    <span class="at">period =</span> <span class="fu">case_when</span>(</span>
<span id="cb4-4"><a href="#cb4-4" aria-hidden="true" tabindex="-1"></a>      date <span class="sc">&gt;=</span> <span class="fu">as.Date</span>(<span class="st">"1978-02-01"</span>) <span class="sc">&amp;</span> date <span class="sc">&lt;=</span> <span class="fu">as.Date</span>(<span class="st">"1989-12-01"</span>) <span class="sc">~</span> <span class="st">"1978–1989"</span>,</span>
<span id="cb4-5"><a href="#cb4-5" aria-hidden="true" tabindex="-1"></a>      date <span class="sc">&gt;=</span> <span class="fu">as.Date</span>(<span class="st">"1990-01-01"</span>) <span class="sc">&amp;</span> date <span class="sc">&lt;=</span> <span class="fu">as.Date</span>(<span class="st">"1994-12-01"</span>) <span class="sc">~</span> <span class="st">"1990–1994"</span>,</span>
<span id="cb4-6"><a href="#cb4-6" aria-hidden="true" tabindex="-1"></a>      date <span class="sc">&gt;=</span> <span class="fu">as.Date</span>(<span class="st">"1995-01-01"</span>) <span class="sc">&amp;</span> date <span class="sc">&lt;=</span> <span class="fu">as.Date</span>(<span class="st">"2007-12-01"</span>) <span class="sc">~</span> <span class="st">"1995–2007"</span>,</span>
<span id="cb4-7"><a href="#cb4-7" aria-hidden="true" tabindex="-1"></a>      date <span class="sc">&gt;=</span> <span class="fu">as.Date</span>(<span class="st">"2008-01-01"</span>) <span class="sc">&amp;</span> date <span class="sc">&lt;=</span> <span class="fu">as.Date</span>(<span class="st">"2019-12-01"</span>) <span class="sc">~</span> <span class="st">"2008–2019"</span>,</span>
<span id="cb4-8"><a href="#cb4-8" aria-hidden="true" tabindex="-1"></a>      date <span class="sc">&gt;=</span> <span class="fu">as.Date</span>(<span class="st">"2020-01-01"</span>) <span class="sc">&amp;</span> date <span class="sc">&lt;=</span> <span class="fu">as.Date</span>(<span class="st">"2021-12-01"</span>) <span class="sc">~</span> <span class="st">"2020–2021"</span>,</span>
<span id="cb4-9"><a href="#cb4-9" aria-hidden="true" tabindex="-1"></a>      date <span class="sc">&gt;=</span> <span class="fu">as.Date</span>(<span class="st">"2022-01-01"</span>) <span class="sc">~</span> <span class="st">"2022–present"</span></span>
<span id="cb4-10"><a href="#cb4-10" aria-hidden="true" tabindex="-1"></a>    )</span>
<span id="cb4-11"><a href="#cb4-11" aria-hidden="true" tabindex="-1"></a>  ) <span class="sc">|&gt;</span></span>
<span id="cb4-12"><a href="#cb4-12" aria-hidden="true" tabindex="-1"></a>  <span class="fu">group_by</span>(period) <span class="sc">|&gt;</span></span>
<span id="cb4-13"><a href="#cb4-13" aria-hidden="true" tabindex="-1"></a>  <span class="fu">summarise</span>(</span>
<span id="cb4-14"><a href="#cb4-14" aria-hidden="true" tabindex="-1"></a>    <span class="at">observations =</span> <span class="fu">n</span>(),</span>
<span id="cb4-15"><a href="#cb4-15" aria-hidden="true" tabindex="-1"></a>    <span class="at">unemployment =</span> <span class="fu">mean</span>(unemployment_rate, <span class="at">na.rm =</span> <span class="cn">TRUE</span>),</span>
<span id="cb4-16"><a href="#cb4-16" aria-hidden="true" tabindex="-1"></a>    <span class="at">underemployment =</span> <span class="fu">mean</span>(underemployment_rate, <span class="at">na.rm =</span> <span class="cn">TRUE</span>),</span>
<span id="cb4-17"><a href="#cb4-17" aria-hidden="true" tabindex="-1"></a>    <span class="at">underutilisation =</span> <span class="fu">mean</span>(underutilisation_rate, <span class="at">na.rm =</span> <span class="cn">TRUE</span>),</span>
<span id="cb4-18"><a href="#cb4-18" aria-hidden="true" tabindex="-1"></a>    <span class="at">.groups =</span> <span class="st">"drop"</span></span>
<span id="cb4-19"><a href="#cb4-19" aria-hidden="true" tabindex="-1"></a>  )</span>
<span id="cb4-20"><a href="#cb4-20" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb4-21"><a href="#cb4-21" aria-hidden="true" tabindex="-1"></a>knitr<span class="sc">::</span><span class="fu">kable</span>(</span>
<span id="cb4-22"><a href="#cb4-22" aria-hidden="true" tabindex="-1"></a>  period_summary,</span>
<span id="cb4-23"><a href="#cb4-23" aria-hidden="true" tabindex="-1"></a>  <span class="at">digits =</span> <span class="dv">2</span>,</span>
<span id="cb4-24"><a href="#cb4-24" aria-hidden="true" tabindex="-1"></a>  <span class="at">col.names =</span> <span class="fu">c</span>(</span>
<span id="cb4-25"><a href="#cb4-25" aria-hidden="true" tabindex="-1"></a>    <span class="st">"Period"</span>,</span>
<span id="cb4-26"><a href="#cb4-26" aria-hidden="true" tabindex="-1"></a>    <span class="st">"Observations"</span>,</span>
<span id="cb4-27"><a href="#cb4-27" aria-hidden="true" tabindex="-1"></a>    <span class="st">"Unemployment (%)"</span>,</span>
<span id="cb4-28"><a href="#cb4-28" aria-hidden="true" tabindex="-1"></a>    <span class="st">"Underemployment (%)"</span>,</span>
<span id="cb4-29"><a href="#cb4-29" aria-hidden="true" tabindex="-1"></a>    <span class="st">"Underutilisation (%)"</span></span>
<span id="cb4-30"><a href="#cb4-30" aria-hidden="true" tabindex="-1"></a>  )</span>
<span id="cb4-31"><a href="#cb4-31" aria-hidden="true" tabindex="-1"></a>)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div id="tbl-slack-periods" class="cell quarto-float quarto-figure quarto-figure-center anchored">
<figure class="quarto-float quarto-float-tbl figure">
<figcaption class="quarto-float-caption-top quarto-float-caption quarto-float-tbl" id="tbl-slack-periods-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
Table&nbsp;1: Average labour-market slack measures by period
</figcaption>
<div aria-describedby="tbl-slack-periods-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
<div class="cell-output-display">
<table class="do-not-create-environment cell caption-top table table-sm table-striped small">
<colgroup>
<col style="width: 15%">
<col style="width: 15%">
<col style="width: 20%">
<col style="width: 23%">
<col style="width: 25%">
</colgroup>
<thead>
<tr class="header">
<th style="text-align: left;">Period</th>
<th style="text-align: right;">Observations</th>
<th style="text-align: right;">Unemployment (%)</th>
<th style="text-align: right;">Underemployment (%)</th>
<th style="text-align: right;">Underutilisation (%)</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td style="text-align: left;">1978–1989</td>
<td style="text-align: right;">143</td>
<td style="text-align: right;">7.37</td>
<td style="text-align: right;">3.36</td>
<td style="text-align: right;">10.73</td>
</tr>
<tr class="even">
<td style="text-align: left;">1990–1994</td>
<td style="text-align: right;">60</td>
<td style="text-align: right;">9.58</td>
<td style="text-align: right;">6.12</td>
<td style="text-align: right;">15.70</td>
</tr>
<tr class="odd">
<td style="text-align: left;">1995–2007</td>
<td style="text-align: right;">156</td>
<td style="text-align: right;">6.52</td>
<td style="text-align: right;">6.60</td>
<td style="text-align: right;">13.13</td>
</tr>
<tr class="even">
<td style="text-align: left;">2008–2019</td>
<td style="text-align: right;">144</td>
<td style="text-align: right;">5.41</td>
<td style="text-align: right;">7.71</td>
<td style="text-align: right;">13.12</td>
</tr>
<tr class="odd">
<td style="text-align: left;">2020–2021</td>
<td style="text-align: right;">24</td>
<td style="text-align: right;">5.80</td>
<td style="text-align: right;">9.32</td>
<td style="text-align: right;">15.12</td>
</tr>
<tr class="even">
<td style="text-align: left;">2022–present</td>
<td style="text-align: right;">55</td>
<td style="text-align: right;">3.96</td>
<td style="text-align: right;">6.19</td>
<td style="text-align: right;">10.16</td>
</tr>
</tbody>
</table>
</div>
</div>
</figure>
</div>
</div>
<p>The period averages show the level and composition of labour market slack have varied considerably across the sample. During 1978-1989, average unemployment was 7.37%, while underemployment averaged 3.36%, resulting in average underutilisation of 10.7%. Labour market slack was higher during 1990-1994, when average unemployment increased to 9.58% and average underutilisation reached 15.7%. The period also recorded a peak unemployment rate o approximately 11.2% and a peak underutilisation rate of approximately 18.2%.</p>
<p>Between 1995 to 2007, average unemployment declined to 6.52%, while average underemployment increased to 6.60%. Average underutilisation was 13.1%. A similar pattern is evident between 2008 and 2019. Average unemployment declined further to 5.41%, while underemployment increased to 7.71%, leaving average underutilisation at approximately 13.1%. These results indicate that reductions in unemployment were not always accompanied by equivalent reductions in broader labour underutilisation.</p>
<p>The COVID-19 period provides a distinct episode of elevated labour underutilisation. Between 2020 and 2021, average unemployment was 5.80%, while average underemployment increased to 9.32%. Average underutilisation reached 15.1%, with a peak of approximately 20.3%. The relatively large increase in underemployment during this period demonstrates the importance of considering insufficient working hours when examining labour market slack during periods of substantial economic disruption.</p>
<p>From 2022 onwards, average unemployment declined to 3.96%, while average underemployment remained at 6.19%. Average underutilisation was 10.2%. These averages indicate a lower level of measured labour underutilisation than in the preceding periods. Hoever, underemployment remained a meaningful component of total underutilisation, reinforcing the limitation of using unemployment alone to represent unused labour capacity. This period is also shorter than the historical intervals considered above, so comparisons should be interpreted with this difference in sample length in mind.</p>
<p>Overakk, the historical analysis demonstrates that labour market slack is not captured fully by unemployment alone. Although periods of elevated slack have generally coincided with higher unemployment, underemployment has also contributed substantially to total labour underutilisation, particularly in more recent periods. Underutilisation therefore provides a broader observable measure for the subsequent analysis, while unemployment and underemployment are retained as separate measures to examine the composition of slack.</p>
<p>These historical patterns provide a basis for examining the relationship between labour market tightness and slack. The next section therefore compares the tightness measure with unemployment, underemployment and underutilisation to assess how these measures move relative to the availability of vacancies per unemployed person.</p>
</section>
<section id="labour-market-tightness-and-slack" class="level2">
<h2 class="anchored" data-anchor-id="labour-market-tightness-and-slack">4.4 Labour-Market Tightness and Slack</h2>
</section>
</section>
<section id="references" class="level1 unnumbered">


</section>

<div id="quarto-appendix" class="default"><section class="quarto-appendix-contents" role="doc-bibliography" id="quarto-bibliography"><h2 class="anchored quarto-appendix-heading">References</h2><div id="refs" class="references csl-bib-body hanging-indent" data-entry-spacing="0" role="list">
<div id="ref-ABS2026JobVacancies" class="csl-entry" role="listitem">
Australian Bureau of Statistics. 2026. <span>“Job Vacancies, Australia Methodology, May 2026.”</span> Australian Bureau of Statistics. <a href="https://www.abs.gov.au/methodologies/job-vacancies-australia-methodology/may-2026">https://www.abs.gov.au/methodologies/job-vacancies-australia-methodology/may-2026</a>.
</div>
<div id="ref-JSAIVIMethodology" class="csl-entry" role="listitem">
Jobs and Skills Australia. n.d. <span>“Internet Vacancy Index Methodology.”</span> Jobs; Skills Australia. <a href="https://www.jobsandskills.gov.au/data/internet-vacancy-index/methodology">https://www.jobsandskills.gov.au/data/internet-vacancy-index/methodology</a>.
</div>
</div></section></div></main>
<!-- /main column -->
<script id="quarto-html-after-body" type="application/javascript">
  window.document.addEventListener("DOMContentLoaded", function (event) {
    const icon = "";
    const anchorJS = new window.AnchorJS();
    anchorJS.options = {
      placement: 'right',
      icon: icon
    };
    anchorJS.add('.anchored');
    const isCodeAnnotation = (el) => {
      for (const clz of el.classList) {
        if (clz.startsWith('code-annotation-')) {                     
          return true;
        }
      }
      return false;
    }
    const onCopySuccess = function(e) {
      // button target
      const button = e.trigger;
      // don't keep focus
      button.blur();
      // flash "checked"
      button.classList.add('code-copy-button-checked');
      var currentTitle = button.getAttribute("title");
      button.setAttribute("title", "Copied!");
      let tooltip;
      if (window.bootstrap) {
        button.setAttribute("data-bs-toggle", "tooltip");
        button.setAttribute("data-bs-placement", "left");
        button.setAttribute("data-bs-title", "Copied!");
        tooltip = new bootstrap.Tooltip(button, 
          { trigger: "manual", 
            customClass: "code-copy-button-tooltip",
            offset: [0, -8]});
        tooltip.show();    
      }
      setTimeout(function() {
        if (tooltip) {
          tooltip.hide();
          button.removeAttribute("data-bs-title");
          button.removeAttribute("data-bs-toggle");
          button.removeAttribute("data-bs-placement");
        }
        button.setAttribute("title", currentTitle);
        button.classList.remove('code-copy-button-checked');
      }, 1000);
      // clear code selection
      e.clearSelection();
    }
    const getTextToCopy = function(trigger) {
      const outerScaffold = trigger.parentElement.cloneNode(true);
      const codeEl = outerScaffold.querySelector('code');
      for (const childEl of codeEl.children) {
        if (isCodeAnnotation(childEl)) {
          childEl.remove();
        }
      }
      return codeEl.innerText;
    }
    const clipboard = new window.ClipboardJS('.code-copy-button:not([data-in-quarto-modal])', {
      text: getTextToCopy
    });
    clipboard.on('success', onCopySuccess);
    if (window.document.getElementById('quarto-embedded-source-code-modal')) {
      const clipboardModal = new window.ClipboardJS('.code-copy-button[data-in-quarto-modal]', {
        text: getTextToCopy,
        container: window.document.getElementById('quarto-embedded-source-code-modal')
      });
      clipboardModal.on('success', onCopySuccess);
    }
      var localhostRegex = new RegExp(/^(?:http|https):\/\/localhost\:?[0-9]*\//);
      var mailtoRegex = new RegExp(/^mailto:/);
        var filterRegex = new RegExp('/' + window.location.host + '/');
      var isInternal = (href) => {
          return filterRegex.test(href) || localhostRegex.test(href) || mailtoRegex.test(href);
      }
      // Inspect non-navigation links and adorn them if external
     var links = window.document.querySelectorAll('a[href]:not(.nav-link):not(.navbar-brand):not(.toc-action):not(.sidebar-link):not(.sidebar-item-toggle):not(.pagination-link):not(.no-external):not([aria-hidden]):not(.dropdown-item):not(.quarto-navigation-tool):not(.about-link)');
      for (var i=0; i<links.length; i++) {
        const link = links[i];
        if (!isInternal(link.href)) {
          // undo the damage that might have been done by quarto-nav.js in the case of
          // links that we want to consider external
          if (link.dataset.originalHref !== undefined) {
            link.href = link.dataset.originalHref;
          }
        }
      }
    function tippyHover(el, contentFn, onTriggerFn, onUntriggerFn) {
      const config = {
        allowHTML: true,
        maxWidth: 500,
        delay: 100,
        arrow: false,
        appendTo: function(el) {
            return el.parentElement;
        },
        interactive: true,
        interactiveBorder: 10,
        theme: 'quarto',
        placement: 'bottom-start',
      };
      if (contentFn) {
        config.content = contentFn;
      }
      if (onTriggerFn) {
        config.onTrigger = onTriggerFn;
      }
      if (onUntriggerFn) {
        config.onUntrigger = onUntriggerFn;
      }
      window.tippy(el, config); 
    }
    const noterefs = window.document.querySelectorAll('a[role="doc-noteref"]');
    for (var i=0; i<noterefs.length; i++) {
      const ref = noterefs[i];
      tippyHover(ref, function() {
        // use id or data attribute instead here
        let href = ref.getAttribute('data-footnote-href') || ref.getAttribute('href');
        try { href = new URL(href).hash; } catch {}
        const id = href.replace(/^#\/?/, "");
        const note = window.document.getElementById(id);
        if (note) {
          return note.innerHTML;
        } else {
          return "";
        }
      });
    }
    const xrefs = window.document.querySelectorAll('a.quarto-xref');
    const processXRef = (id, note) => {
      // Strip column container classes
      const stripColumnClz = (el) => {
        el.classList.remove("page-full", "page-columns");
        if (el.children) {
          for (const child of el.children) {
            stripColumnClz(child);
          }
        }
      }
      stripColumnClz(note)
      if (id === null || id.startsWith('sec-')) {
        // Special case sections, only their first couple elements
        const container = document.createElement("div");
        if (note.children && note.children.length > 2) {
          container.appendChild(note.children[0].cloneNode(true));
          for (let i = 1; i < note.children.length; i++) {
            const child = note.children[i];
            if (child.tagName === "P" && child.innerText === "") {
              continue;
            } else {
              container.appendChild(child.cloneNode(true));
              break;
            }
          }
          if (window.Quarto?.typesetMath) {
            window.Quarto.typesetMath(container);
          }
          return container.innerHTML
        } else {
          if (window.Quarto?.typesetMath) {
            window.Quarto.typesetMath(note);
          }
          return note.innerHTML;
        }
      } else {
        // Remove any anchor links if they are present
        const anchorLink = note.querySelector('a.anchorjs-link');
        if (anchorLink) {
          anchorLink.remove();
        }
        if (window.Quarto?.typesetMath) {
          window.Quarto.typesetMath(note);
        }
        if (note.classList.contains("callout")) {
          return note.outerHTML;
        } else {
          return note.innerHTML;
        }
      }
    }
    for (var i=0; i<xrefs.length; i++) {
      const xref = xrefs[i];
      tippyHover(xref, undefined, function(instance) {
        instance.disable();
        let url = xref.getAttribute('href');
        let hash = undefined; 
        if (url.startsWith('#')) {
          hash = url;
        } else {
          try { hash = new URL(url).hash; } catch {}
        }
        if (hash) {
          const id = hash.replace(/^#\/?/, "");
          const note = window.document.getElementById(id);
          if (note !== null) {
            try {
              const html = processXRef(id, note.cloneNode(true));
              instance.setContent(html);
            } finally {
              instance.enable();
              instance.show();
            }
          } else {
            // See if we can fetch this
            fetch(url.split('#')[0])
            .then(res => res.text())
            .then(html => {
              const parser = new DOMParser();
              const htmlDoc = parser.parseFromString(html, "text/html");
              const note = htmlDoc.getElementById(id);
              if (note !== null) {
                const html = processXRef(id, note);
                instance.setContent(html);
              } 
            }).finally(() => {
              instance.enable();
              instance.show();
            });
          }
        } else {
          // See if we can fetch a full url (with no hash to target)
          // This is a special case and we should probably do some content thinning / targeting
          fetch(url)
          .then(res => res.text())
          .then(html => {
            const parser = new DOMParser();
            const htmlDoc = parser.parseFromString(html, "text/html");
            const note = htmlDoc.querySelector('main.content');
            if (note !== null) {
              // This should only happen for chapter cross references
              // (since there is no id in the URL)
              // remove the first header
              if (note.children.length > 0 && note.children[0].tagName === "HEADER") {
                note.children[0].remove();
              }
              const html = processXRef(null, note);
              instance.setContent(html);
            } 
          }).finally(() => {
            instance.enable();
            instance.show();
          });
        }
      }, function(instance) {
      });
    }
        let selectedAnnoteEl;
        const selectorForAnnotation = ( cell, annotation) => {
          let cellAttr = 'data-code-cell="' + cell + '"';
          let lineAttr = 'data-code-annotation="' +  annotation + '"';
          const selector = 'span[' + cellAttr + '][' + lineAttr + ']';
          return selector;
        }
        const selectCodeLines = (annoteEl) => {
          const doc = window.document;
          const targetCell = annoteEl.getAttribute("data-target-cell");
          const targetAnnotation = annoteEl.getAttribute("data-target-annotation");
          const annoteSpan = window.document.querySelector(selectorForAnnotation(targetCell, targetAnnotation));
          const lines = annoteSpan.getAttribute("data-code-lines").split(",");
          const lineIds = lines.map((line) => {
            return targetCell + "-" + line;
          })
          let top = null;
          let height = null;
          let parent = null;
          if (lineIds.length > 0) {
              //compute the position of the single el (top and bottom and make a div)
              const el = window.document.getElementById(lineIds[0]);
              top = el.offsetTop;
              height = el.offsetHeight;
              parent = el.parentElement.parentElement;
            if (lineIds.length > 1) {
              const lastEl = window.document.getElementById(lineIds[lineIds.length - 1]);
              const bottom = lastEl.offsetTop + lastEl.offsetHeight;
              height = bottom - top;
            }
            if (top !== null && height !== null && parent !== null) {
              // cook up a div (if necessary) and position it 
              let div = window.document.getElementById("code-annotation-line-highlight");
              if (div === null) {
                div = window.document.createElement("div");
                div.setAttribute("id", "code-annotation-line-highlight");
                div.style.position = 'absolute';
                parent.appendChild(div);
              }
              div.style.top = top - 2 + "px";
              div.style.height = height + 4 + "px";
              div.style.left = 0;
              let gutterDiv = window.document.getElementById("code-annotation-line-highlight-gutter");
              if (gutterDiv === null) {
                gutterDiv = window.document.createElement("div");
                gutterDiv.setAttribute("id", "code-annotation-line-highlight-gutter");
                gutterDiv.style.position = 'absolute';
                const codeCell = window.document.getElementById(targetCell);
                const gutter = codeCell.querySelector('.code-annotation-gutter');
                gutter.appendChild(gutterDiv);
              }
              gutterDiv.style.top = top - 2 + "px";
              gutterDiv.style.height = height + 4 + "px";
            }
            selectedAnnoteEl = annoteEl;
          }
        };
        const unselectCodeLines = () => {
          const elementsIds = ["code-annotation-line-highlight", "code-annotation-line-highlight-gutter"];
          elementsIds.forEach((elId) => {
            const div = window.document.getElementById(elId);
            if (div) {
              div.remove();
            }
          });
          selectedAnnoteEl = undefined;
        };
          // Handle positioning of the toggle
      window.addEventListener(
        "resize",
        throttle(() => {
          elRect = undefined;
          if (selectedAnnoteEl) {
            selectCodeLines(selectedAnnoteEl);
          }
        }, 10)
      );
      function throttle(fn, ms) {
      let throttle = false;
      let timer;
        return (...args) => {
          if(!throttle) { // first call gets through
              fn.apply(this, args);
              throttle = true;
          } else { // all the others get throttled
              if(timer) clearTimeout(timer); // cancel #2
              timer = setTimeout(() => {
                fn.apply(this, args);
                timer = throttle = false;
              }, ms);
          }
        };
      }
        // Attach click handler to the DT
        const annoteDls = window.document.querySelectorAll('dt[data-target-cell]');
        for (const annoteDlNode of annoteDls) {
          annoteDlNode.addEventListener('click', (event) => {
            const clickedEl = event.target;
            if (clickedEl !== selectedAnnoteEl) {
              unselectCodeLines();
              const activeEl = window.document.querySelector('dt[data-target-cell].code-annotation-active');
              if (activeEl) {
                activeEl.classList.remove('code-annotation-active');
              }
              selectCodeLines(clickedEl);
              clickedEl.classList.add('code-annotation-active');
            } else {
              // Unselect the line
              unselectCodeLines();
              clickedEl.classList.remove('code-annotation-active');
            }
          });
        }
    const findCites = (el) => {
      const parentEl = el.parentElement;
      if (parentEl) {
        const cites = parentEl.dataset.cites;
        if (cites) {
          return {
            el,
            cites: cites.split(' ')
          };
        } else {
          return findCites(el.parentElement)
        }
      } else {
        return undefined;
      }
    };
    var bibliorefs = window.document.querySelectorAll('a[role="doc-biblioref"]');
    for (var i=0; i<bibliorefs.length; i++) {
      const ref = bibliorefs[i];
      const citeInfo = findCites(ref);
      if (citeInfo) {
        tippyHover(citeInfo.el, function() {
          var popup = window.document.createElement('div');
          citeInfo.cites.forEach(function(cite) {
            var citeDiv = window.document.createElement('div');
            citeDiv.classList.add('hanging-indent');
            citeDiv.classList.add('csl-entry');
            var biblioDiv = window.document.getElementById('ref-' + cite);
            if (biblioDiv) {
              citeDiv.innerHTML = biblioDiv.innerHTML;
            }
            popup.appendChild(citeDiv);
          });
          return popup.innerHTML;
        });
      }
    }
  });
  </script>
</div> <!-- /content -->




</body></html>